### ISSUE TITLE
Copy buttons not working

### ISSUE THREAD

**Issue by lonnylundsten** [mbari-media-management/vars-annotation#8]
The buttons in the GUI for 'copy annotation' and 'copy annotations using current video index' are not working.

**Comment by hohonuuli** [comment]
Whoops, I forgot to wipe the primary key when I cloned the associations. The database doesn't like that ...

```
Internal Exception: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__associat__7F427930BE1BC31E'. Cannot insert duplicate key in object 'dbo.associations'. The duplicate key value is (149357cd-b6c8-41d8-aa4c-de59b7d57ed9).
Error Code: 2627
Call: INSERT INTO associations (uuid, last_updated_timestamp, link_name, link_value, mime_type, to_concept, observation_uuid) VALUES (?, ?, ?, ?, ?, ?, ?)
	bind => [7 parameters bound]
Query: InsertObjectQuery(comment | human | wow)
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:879)
	at org.eclipse.persistence.internal.jpa.QueryImpl.performPreQueryFlush(QueryImpl.java:967)
	at org.eclipse.persistence.internal.jpa.QueryImpl.executeReadQuery(QueryImpl.java:207)
	at org.eclipse.persistence.internal.jpa.QueryImpl.getResultList(QueryImpl.java:473)
	at org.mbari.vars.annotation.dao.jpa.BaseDAO.findByNamedQuery(BaseDAO.scala:44)
	at org.mbari.vars.annotation.dao.jpa.ImageReferenceDAOImpl.findByURL(ImageReferenceDAOImpl.scala:44)
	at org.mbari.vars.annotation.controllers.AnnotationController.$anonfun$create$8(AnnotationController.scala:124)
	at org.mbari.vars.annotation.controllers.AnnotationController.$anonfun$create$8$adapted(AnnotationController.scala:123)
	at scala.collection.Iterator.foreach(Iterator.scala:929)

```

**Comment by hohonuuli** [comment]
I added a resetUuid method to associations that can be called to null out the primary key.
